# Generated by Django 4.1.7 on 2023-03-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic_url',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
