# Generated by Django 4.1.7 on 2023-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_application', '0002_book_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='book_author_last_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
