# Generated by Django 4.1.7 on 2023-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_application', '0003_alter_hold_book_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic_url',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hold',
            name='book_author_last_name',
            field=models.CharField(max_length=100),
        ),
    ]
